### ISSUE TITLE
Sporadic "NoMethodError: undefined method `[]' for nil:NilClass" when authenticating

### ISSUE THREAD

**Issue by daveespo** [ejholmes/restforce#131]
We've been using the restforce gem for ages (currently 1.4.3). Within the past 2 months, our background jobs that do periodic API calls to Salesforce started failing with:

````
NoMethodError: undefined method `[]' for nil:NilClass
        from /opt/ruby/lib/ruby/gems/2.0.0/bundler/gems/restforce-872304c07d47/lib/restforce/middleware/authentication.rb:50:in `error_message'
        from /opt/ruby/lib/ruby/gems/2.0.0/bundler/gems/restforce-872304c07d47/lib/restforce/middleware/authentication.rb:24:in `authenticate!'
        from /opt/ruby/lib/ruby/gems/2.0.0/bundler/gems/restforce-872304c07d47/lib/restforce/concerns/authentication.rb:9:in `authenticate!'
````

I forked restforce and added some debug output and have captured the following Faraday response when this condition occurs. Notice the status=302, body=nil and location=>'/?ec=999'

````
 #<Faraday::Response:0x007eff3225ef58 @env={:method=>:post, :body=>nil, :url=>#<URI::HTTPS:0x007eff3224d9b0 URL:https://test.salesforce.com/services/oauth2/token>, :request_headers=>{"User-Agent"=>"Faraday v0.8.9", "Content-Type"=>"application/x-www-form-urlencoded"}, :parallel_manager=>nil, :request=>{:proxy=>nil}, :ssl=>{}, :status=>302, :response_headers=>{"date"=>"Tue, 09 Sep 2014 15:27:30 GMT", "set-cookie"=>"BrowserId=OCbdVSRSQCi-jvhLMsohdA;Path=/;Domain=.salesforce.com;Expires=Sat, 08-Nov-2014 15:27:30 GMT", "expires"=>"Thu, 01 Jan 1970 00:00:00 GMT", "pragma"=>"no-cache", "cache-control"=>"no-cache, no-store", "location"=>"/?ec=999", "transfer-encoding"=>"chunked", "connection"=>"close"}, :response=>#<Faraday::Response:0x007eff3225ef58 ...>}, @on_complete_callbacks=[]>
NoMethodError: undefined method `[]' for nil:NilClass
        from /opt/ruby/lib/ruby/gems/2.0.0/bundler/gems/restforce-872304c07d47/lib/restforce/middleware/authentication.rb:50:in `error_message'
        from /opt/ruby/lib/ruby/gems/2.0.0/bundler/gems/restforce-872304c07d47/lib/restforce/middleware/authentication.rb:24:in `authenticate!'
        from /opt/ruby/lib/ruby/gems/2.0.0/bundler/gems/restforce-872304c07d47/lib/restforce/concerns/authentication.rb:9:in `authenticate!'
````

Pulling down the body from this redirection url (https://test.salesforce.com/services/oauth2/token?ec=999) yields:

````
<OAuth>
<error_description>grant type not supported</error_description>
<error>unsupported_grant_type</error>
</OAuth>
````

Log output from when Restforce.log is turned on:

````
  url: "https://test.salesforce.com/services/oauth2/token"
  method: :post
  headers: {"User-Agent"=>"Faraday v0.8.9", "Content-Type"=>"application/x-www-form-urlencoded"}
  body: "grant_type=refresh_token&refresh_token=***&client_id=***&client_secret=***"

  status: "302"
  headers: {"date"=>"Tue, 09 Sep 2014 16:14:37 GMT", "set-cookie"=>"BrowserId=iEGb-mC0SRyLjfhBcDpUCQ;Path=/;Domain=.salesforce.com;Expires=Sat, 08-Nov-2014 16:14:37 GMT", "expires"=>"Thu, 01 Jan 1970 00:00:00 GMT", "pragma"=>"no-cache", "cache-control"=>"no-cache, no-store", "location"=>"/?ec=999", "transfer-encoding"=>"chunked", "connection"=>"close"}
  body: ""
RAW ERROR RESPONSE: #<Faraday::Response:0x007fb54b5bfa38 @env={:method=>:post, :body=>nil, :url=>#<URI::HTTPS:0x007fb54b5aeb20 URL:https://test.salesforce.com/services/oauth2/token>, :request_headers=>{"User-Agent"=>"Faraday v0.8.9", "Content-Type"=>"application/x-www-form-urlencoded"}, :parallel_manager=>nil, :request=>{:proxy=>nil}, :ssl=>{}, :status=>302, :response_headers=>{"date"=>"Tue, 09 Sep 2014 16:14:37 GMT", "set-cookie"=>"BrowserId=iEGb-mC0SRyLjfhBcDpUCQ;Path=/;Domain=.salesforce.com;Expires=Sat, 08-Nov-2014 16:14:37 GMT", "expires"=>"Thu, 01 Jan 1970 00:00:00 GMT", "pragma"=>"no-cache", "cache-control"=>"no-cache, no-store", "location"=>"/?ec=999", "transfer-encoding"=>"chunked", "connection"=>"close"}, :response=>#<Faraday::Response:0x007fb54b5bfa38 ...>}, @on_complete_callbacks=[]>
NoMethodError: undefined method `[]' for nil:NilClass
        from /opt/ruby/lib/ruby/gems/2.0.0/bundler/gems/restforce-872304c07d47/lib/restforce/middleware/authentication.rb:50:in `error_message'
        from /opt/ruby/lib/ruby/gems/2.0.0/bundler/gems/restforce-872304c07d47/lib/restforce/middleware/authentication.rb:24:in `authenticate!'
        from /opt/ruby/lib/ruby/gems/2.0.0/bundler/gems/restforce-872304c07d47/lib/restforce/concerns/authentication.rb:9:in `authenticate!'
        from /home/vagrant/project/app/models/payment_transaction.rb:435:in `ptech_client'
        from (irb):1
        from /opt/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.17/lib/rails/commands/console.rb:47:in `start'
        from /opt/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in `start'
        from /opt/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.17/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
````

I can't find any documentation on what this could be indicating. When this condition occurs, it takes it a good 15 seconds to ultimately fail so I suspect this is some internal Salesforce timeout. If I re-run the exact same code, it generally succeeds 9 times out of 10. It happens on both the sandbox login URL and production.

I can participate in authoring a patch to more gracefully handle this condition, but I don't know how we should handle it. If I just fix up authentication.rb to not yack on the nil response body, that will cause an AuthenticationError which may or may not be the right experience for the client code. Alternatively, I could follow the redirect.

Opinions?

**Comment by daveespo** [comment]
I don't want to declare victory here prematurely, but I haven't seen a single instance of this in our production code since December 16 -- no changes to our code could explain the change in behavior so I have to chalk this up to Salesforce hot patch 

I'll close this ticket for now and reopen it if we see it again

**Comment by Fire-Dragon-DoL** [comment]
@daveespo I probably found the reason, it's a permission issue on salesforce end which returns an unexpected response type. I didn't manage to trigger it anyway.

**Comment by daveespo** [comment]
Interesting .. though it seemed more like a bug than a repeatable 'undocumented feature' since the same connection attempt against the same org would succeed the second (or third) time. Also, there was a measurable latency in the request/response time so I'm still pretty sure this was an internal timeout that was being badly propagated back to the client

**Comment by Fire-Dragon-DoL** [comment]
@daveespo it definitely could. Actually more general, it was an issue with an unexpected response. So it may not be directly related to a permission issue, but even to an error (which resulted in an unexpected response)

**Comment by daveespo** [comment]
Now that the problem went away, I'm not eager to "make work" but it would aid immensely in debugging if Restforce could protect against an unexpected response (in this case, I believe it was a nil response body from Faraday) and at least propagate the whole schmeer back up to the caller via an Exception. Maybe some day down the road...

**Comment by Fire-Dragon-DoL** [comment]
:+1:

**Comment by andrewr224** [comment]
Issue is still reproduced. My restforce version is 3.1.0, everything else matches daveespo's description
