### ISSUE TITLE
Possible memory leak (growth) with Streaming API

### ISSUE THREAD

**Issue by muratonder** [ejholmes/restforce#176]
After running the client more than a day now with a simple subscription to a Push topic on Salesforce, just like the way in ReadMe, there is an increasing pattern in memory usage. Did anyone come across this issue? Below is the contents of the Gemfile, I'm running the client against Salesforce API version 32.0.

# Gemfile
source "https://rubygems.org"

gem 'cookiejar', :git => 'https://github.com/MissionCapital/cookiejar.git'
gem 'restforce'
gem 'faye', '0.8.9'
gem 'mysql2'
gem 'json'

Thanks.

**Comment by thbar** [comment]
I'm starting to use the streaming API. Did you end up understanding what happened here? Thanks!

**Comment by muratonder** [comment]
I have changed the implementation long time ago, nor using the Streaming API anymore.. Cheers.
