### ISSUE TITLE
Return object instead of string

### ISSUE THREAD

**Issue by demonmind** [ejholmes/restforce#180]
Hi,

When i use `create` to create a lead or contact, it always returns just the Id of the entity being created. Is there a way to return the object with all fields so I don't have to make an extra request to get the other details I need to display?

**Comment by theSteveMitchell** [comment]
This isn't possible with Salesforce's api, without an extra request.  
https://www.salesforce.com/us/developer/docs/api_rest/Content/dome_sobject_create.htm

The Salesforce create API only returns
```json
{
    "id" : "001D000000IqhSLIAZ",
    "errors" : [ ],
    "success" : true
}
```

So restforce would have to make a second request internally, which would be inefficient.  Besides, if you're creating the object, you should already have all the attributes locally.

**Comment by demonmind** [comment]
Sounds good, thank you.
