### ISSUE TITLE
What's the real benefit of refresh token vs other methods of authenticating (username/password)?

### ISSUE THREAD

**Issue by antwonlee** [ejholmes/restforce#181]
What's the real benefit of refresh token vs other methods of authenticating (username/password)?

**Comment by theSteveMitchell** [comment]
by other methods, I'm assuming you mean username/password

Two main benefits that I see:
1. As demonstrated in #171, performance improves with refresh token auth, especially when the token can be cached.  Perhaps we should move that caching into Restforce.  

2. Your application does not need the usename/password combination to authenticate, if it has instead a refresh token.  Consider my application:  We have an Ember.js app and a mobile IOS app that share the same API.  Both use the user-agent flow outlined here https://help.salesforce.com/HTViewHelpDoc?id=remoteaccess_authenticate.htm to authenticate with Salesforce.  When either client requests an action from our api, they pass the user's refresh token, so the api can access Salesforce on the user's behalf.  We manage some custom workflows this way.  If the clients had to always pass username and password on each request, it would be less efficient, less secure, and would be more difficult to manage session timeouts.  If your application only uses a single account, than this doesn't really affect you though.

**Comment by antwonlee** [comment]
Thanks @theSteveMitchell, that was a great explanation.  As for #171 this was a great resource for me: https://www.youtube.com/watch?v=D5OsrRisNxA

**Comment by theSteveMitchell** [comment]
good to close this?
