### ISSUE TITLE
Restforce CometD connection degrades over time

### ISSUE THREAD

**Issue by smzchaudary** [ejholmes/restforce#194]
On my local development machine, I am seeing a stable CometD connection of about 1 minute between `COMETD UP` and `COMETD DOWN` messages.

As an aside, that seems very short to begin with.

However, after deploying to an ec2 instance in AWS, I am seeing that connection slowly degrade, eventually down to the connection being up for only 1-2 seconds.

```
D, [2015-07-09T15:11:07.702916 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:12:19.701093 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:13:10.973763 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:14:22.793086 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:14:27.987411 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:15:09.420705 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:15:14.922415 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:15:39.820389 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:15:44.986111 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:16:26.765462 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:16:31.909075 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:16:56.840699 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:17:02.004995 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:17:13.105245 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:17:18.564525 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:17:43.792276 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:17:48.986450 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:18:13.864538 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:18:19.029704 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:18:30.396848 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:18:35.588754 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:19:00.819996 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:19:05.956041 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:19:16.738989 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:19:22.090076 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:19:30.875752 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:19:36.065752 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:19:47.407385 #289] DEBUG -- : [COMETD DOWN]
D, [2015-07-09T15:19:52.570507 #289] DEBUG -- : [COMETD UP]
D, [2015-07-09T15:20:17.848773 #289] DEBUG -- : [COMETD DOWN]
```

Gemfile.lock relevant lines:
```
$ grep restforce Gemfile.lock
    restforce (2.1.0)
  restforce
```

```
$ grep faye Gemfile.lock
    faye (1.1.1)
      faye-websocket (>= 0.9.1)
    faye-websocket (0.9.2)
  faye
```
As a secondary issue, which maybe due to constant reconnections, I sometimes get a `400` on the authentication call, with `invalid_grant` as the error detail.

Any insight into how to resolve this issue would be greatly appreciated.
I have included relevant code samples bellow - but can provide more details if needed.

```
  def client
    @_client ||= create_client
  end

  def create_client
    logger.info("Creating Client")
    Restforce.log = true
    Restforce.configure do |config|
      config.logger = Logger.new(RESTFORCE_LOGFILE)
      config.log_level = :info
    end

    c = Restforce.new
    c.authenticate!
    c
  end

    def add_push_topic(topic_name, topic_query, topic_action_proc)
      push_topics[topic_name] = { query: topic_query, action: topic_action_proc }
    end

    def subscribe_to_topics
      EM.run do
        Signal.trap('INT')  { EM.stop }
        Signal.trap('TERM') { EM.stop }

        push_topics.each do |name, value|
          client.subscribe name do |message|
            value[:action].call(message)
          end
        end
      end
    end
```

*UPDATE:* Seems to be an issue between faye client and the Salesforce server
I am seeing this once I attached the faye debugger
```
[Faye::Client] Passing through incoming extensions: {"clientId":"redacted","error":"403::Unknown client","successful":false}
```

**Comment by smzchaudary** [comment]
Seems related to the newer versions of faye.
Rolled back down to `0.8.9` and the connections seems stable - and does not disconnect after an hour.
What is the status of https://github.com/ejholmes/restforce/issues/114? It says its open, and can be used against the master branch of `faye/faye` - but the commit in faye in question is available in `1.1.0` and `1.1.1` - and I have the same issues when using those tags.

**Comment by smzchaudary** [comment]
Giving a quick update: after rolling back to faye `0.8.9`, the connection is stable, and the last `COMETD UP` message was about 20 hours ago, and updates are coming through.

**Comment by greenmindPDX** [comment]
@smzchaudary thanks for reporting on this! I just stumbled on the same problem with faye version 1.x, and reverting to faye `0.8.9` made all the difference.

**Comment by smzchaudary** [comment]
@greenmindPDX glad downgrading worked for you.

I tried looking at the project README and documentation, but I don't see any caveat that the version of faye needs to be `0.8.9` - I think thats a pretty important omission due to the fact that subscribing to push topics will simply not work `out of the box` with  the latest versions of faye.

**Comment by greenmindPDX** [comment]
@smzchaudary :+1: 

I would agree that this should make it into the README. It may be that users aren't using the streaming API that much, or that streaming is working just enough of the time in later versions of Faye to be ignored. I had some connectivity with later versions, but `0.8.9` is bombproof.

**Comment by timrogers** [comment]
I'm open to putting this in the README. Do one of you guys want to make a
PR?

--

*Tim Rogers*
GoCardless.com <https://gocardless.com>

**Comment by smzchaudary** [comment]
@timrogers OK, PR created - https://github.com/ejholmes/restforce/pull/207.
