### ISSUE TITLE
Invoices & Other Entitites

### ISSUE THREAD

**Issue by seanhandley** [ejholmes/restforce#195]
Any documentation on how you create other entities besides Accounts would be greatly appreciated.

The Salesforce documentation is tragically poor.

**Comment by antwonlee** [comment]
Salesforce actually has great documentation :grinning:  

You can query or create by the Salesforce Object API name and fields you created in that object.

```client.create('Object_Name__c', FieldName: 'Foobar Inc.')```

**Comment by seanhandley** [comment]
Thanks @antwonlee. The trouble is knowing ahead of time what the objects and fields are going to be called.

I've found you can create invoices as follows:

```ruby
args = {
c2g__Account__c: "001b0000015mClw",
c2g__InvoiceDate__c: "2015-11-25",
c2g__InvoiceCurrency__c: 'a0Jb000000ll9AHEAY',
c2g__DueDate__c: "2015-11-25"
}
Restforce.new.create!('c2g__codaInvoice__c', args)
```

Using `create!` with a bang has been a godsend in figuring out which fields are missing, though not always what the data type is prepared to accept.
