### ISSUE TITLE
client.limits returns an error

### ISSUE THREAD

**Issue by alker7** [ejholmes/restforce#197]
I'm calling the limits method (*after setting client to version 32*) and get an error 

`NoMethodError: undefined method `limits' for #<Restforce::Data::Client:0x007fddb4d874f0>`

    def get_sfdc_api_limits
      client = get_restforce_client
      org_describe = client.describe   # works
      api_limits = client.limits       # crashes
    end

**Comment by web-connect** [comment]
What version of the gem are you using? And do you have the SalesForce API Version set to 29 or higher?

**Comment by timrogers** [comment]
Sounds most likely to be a gem version problem to me, as @web-connect suggests. Make sure you're using the latest version - or perhaps try including it from GitHub (it could be that the version with `limits` isn't on Rubygems).

**Comment by alker7** [comment]
Tim, you were right.
instead of
`gem 'restforce'`
I put
`gem 'restforce', git: 'https://github.com/ejholmes/restforce.git'`
to my Gemfile. This is resolved. Thanks

**Comment by timrogers** [comment]
@alker7 No worries! I've just released a v2.1.1 now so you can start loading from Rubygems again.
