### ISSUE TITLE
Client search method doesn't automatically escape SOSL reserved chars

### ISSUE THREAD

**Issue by moskeyombus** [ejholmes/restforce#203]
According to SOSL reference docs, search FIND clauses containing SOSL reserved chars need to be escaped: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_sosl_find.htm

If I try to search for a Contact by email using the following query, I get nothing back:
`"FIND {test+email@test.com} RETURNING Contact (FirstName,LastName)"`

If I escape special chars in the FIND clause, my search works:
`"FIND {test\\+email@test.com} RETURNING Contact (FirstName,LastName)"`

Is this something Restforce should handle?  Or is it intentional that the end user should do their own escaping?  If Restforce should handle this, I'd be happy to open a PR.

**Comment by timrogers** [comment]
Hmm, it's a difficult one - I'm sure where whether I think this should be
handled by the library or not.

@greysteil Would be interested to hear your thoughts when you have a second!

--

*Tim Rogers*
GoCardless.com <https://gocardless.com>

**Comment by greysteil** [comment]
Is there any value in letting the unescaped string through? If you don't escape a `+` for example, what does it do? If the answer isn't "nothing" then I wouldn't handle this in the library.

**Comment by moskeyombus** [comment]
Ah good call, for some reason I thought the search endpoint wasn't actually using those special characters but I misunderstood the responses I was getting.  Thanks!
