### ISSUE TITLE
Update to Lead seems to Inadvertently Change OwnerId

### ISSUE THREAD

**Issue by githoov** [ejholmes/restforce#204]
The following call changes the owner_id:
```
> to_put.first
=> ["00QE000000pMv4XMAS", 0.9467167848012477] 

> to_put.each do |id, probability|
>   client.update('Lead', meeting_probability__c: probability, Id: id)
> end
```
![image](https://cloud.githubusercontent.com/assets/2467394/9745929/875c083a-5629-11e5-94fe-bc74ca7336ca.png)

I'm not sure if this affects other SFDC objects or non-custom fields, but this seems unusual. Note, that a manual change in Lead record does not exhibit the same behavior.

**Comment by timrogers** [comment]
That shouldn't be happening, and it definitely doesn't occur where we're using the library in production. I wonder if it could be some kind of setting on your account? It might be worth asking Salesforce I reckon as the code you're using won't be changing it.

**Comment by githoov** [comment]
That must be it. Thanks @timrogers!
