### ISSUE TITLE
Parse body only if response header specify it

### ISSUE THREAD

**Issue by kouno** [ejholmes/restforce#208]
I'm using a custom APEX REST endpoint and when this endpoint validation fails, it returns a 500 and the body is a simple string.

It looks like Restforce is not checking the `Content-Type` header before parsing the body:

https://github.com/ejholmes/restforce/blob/66ef4acdd0517e7b31a4105af242c1948723157f/lib/restforce/middleware/raise_error.rb#L23

**Comment by timrogers** [comment]
Good spot Vincent. Feel free to write a PR with specs to fix this!

--

*Tim Rogers*
GoCardless.com <https://gocardless.com>

**Comment by kouno** [comment]
Ahah, I swear, that's on my plates :).
