### ISSUE TITLE
Question: best practices for initialization in rails?

### ISSUE THREAD

**Issue by andreimoment** [ejholmes/restforce#213]
I am using restforce to query SF information in conjunction with registration form pre-population and registration. I use username/password authentication as I don't have a need for authenticating users -- all I need is SF query/updates.

I read the warning about thread safety and am wondering what is the best way to initialize the client in a case like mine? Currently I initialize a new client with each request, but this seems wasteful and takes over 700ms. Would it be OK to initialize a client inside an initializer and reuse that client? In what situations should I be worrying about thread safety?

My application runs on Puma/heroku and uses multiple workers but not multithreading.

**Comment by antwonlee** [comment]
@andreimoment would this not work for you? https://github.com/ejholmes/restforce/issues/171

**Comment by kimyu92** [comment]
@antwonlee I am curious about is there any consequences or effeciency difference of only initializing once and then use it as long as I want
```ruby
def get_client
  @client ||= Restforce.new :username => 'foo',
    :password       => 'bar',
    :security_token => 'security token',
    :client_id      => 'client_id',
    :client_secret  => 'client_secret'
end
```

**Comment by antwonlee** [comment]
@theSteveMitchell explains it well here: https://github.com/ejholmes/restforce/issues/171#issuecomment-74299774 I think.  Using memoization to your oauth token will improve any requests after the initial request.  At least it did improve the app I was working on.  @kimyu92 Have you tried any tests to see improvements on your app?

**Comment by kimyu92** [comment]
@antwonlee It works but I am unsure whether I actually need to cache the oauth token since memoizing client works great for me and I did not realize changes made on the oauth token, even if it expired, it would re-authenticate anyway right? Correct me if I'm wrong

**Comment by antwonlee** [comment]
Yeah, I think you are right @kimyu92, even expired it will re-authenticate with your username and password and it will fetch the new oauth token.

Back to the original question, I do wonder how @andreimoment approached his question.

I think it will be good to have an example in README to have thread safe and optimized way of initializing the client.

**Comment by theSteveMitchell** [comment]
@kimyu92 There is a fairly simple way to test the performance improvement.  In Rails console:

Control Test:
```ruby
Restforce.log = true # will log all http requests
client = Restforce.new
client.query("select count() from user")
## results in 2 http requests
## ctrl + k to clear terminal

client = Restforce.new
client.query("select count() from user")
## results in 2 new http requests
```

Cache Test 1:
```console
Restforce.log = true # will log all http requests
client = Restforce.new
client.query("select count() from user")
## results in 2 http requests
## ctrl + k to clear terminal
Rails.cache.write('salesforceforce_oauth_token', client.options[:oauth_token])

client = Restforce.new(:oauth_token => Rails.cache.read('salesforceforce_oauth_token'))
client.query("select count() from user")
## results in 2 new http requests...test failed
```

Cache Test 2:
```console
Restforce.log = true # will log all http requests
client = Restforce.new
client.query("select count() from user")
## results in 2 http requests
## ctrl + k to clear terminal
Rails.cache.write('salesforceforce_oauth_token', client.options[:oauth_token])
Rails.cache.write('salesforceforce_instance_url', client.options[:instance_url])

client = Restforce.new(:oauth_token => Rails.cache.read('salesforceforce_oauth_token'), :instance_url => Rails.cache.read('salesforceforce_instance_url'))
client.query("select count() from user")
## results in only 1 new http request!! Test passed
```

In Cache test 1, you'll see that Restforce still needs to make 2 requests on the second query, because it needs to know the instance URL to query.  In Cache test 2, it will make only a single request for the second query.

In #171 my answer was incomplete, I think because I had hard-coded the instance url in my app config.  That was acceptable at the time, but Salesforce since changed it's recommendations.  

You can also try:
```ruby
client = Restforce.new(:oauth_token => "expired", :instance_url => Rails.cache.read('salesforceforce_instance_url'))
client.query("select count() from user")
```

You'll see that the first GET request responds with 401 "Session expired or invalid", and restforce will renegotiate the oauth token.  The query still succeeds, but it takes 3 requests this time.  So yes, passing an expired token will re-auth automatically.

You can do your own test to show if caching the entire client works.  For me, yes it did.  Even if my cached client has an expired token, it will automatically updated when restforce re-auths.

**Comment by kimyu92** [comment]
> You can do your own test to show if caching the entire client works. For me, yes it did. Even if my cached client has an expired token, it will automatically update when restforce re-auths. My personal preference was to cache only the string values I needed to cache.

Great summary at the end 👍 

@theSteveMitchell thanks again for your insightful explanation!

**Comment by timrogers** [comment]
Kudos to @theSteveMitchell for the above :heart: I'm going to close this now - feel free to add a comment about caching/memoisation in the readme!
