### ISSUE TITLE
Question: Are there more-verbose log levels than :debug?

### ISSUE THREAD

**Issue by nat** [ejholmes/restforce#215]
With log_level set at :debug, when I am trying to create a particular object in salesforce, I am merely receiving a response of "false". Thus, I cannot tell what is causing the creation issue (e.g: is there a required field I'm missing, is a key wrong, etc..).  Is there a symbol I can use to set the log-level more-verbosely or other method so I can see the error details?  Thanks!

**Comment by timrogers** [comment]
Have you tried using the bang (`!`) methods? From memory, they provide
exceptions with more specific details. If you look at how those exceptions
are generated (check the middlewares, from what I remember), you might be
able to add some code that improves the `:debug` logging with a quick PR.

--

*Tim Rogers*
GoCardless.com <https://gocardless.com>

**Comment by nat** [comment]
I haven't tried them - I will try on Monday! Thank you!

**Comment by nat** [comment]
It worked - thank you!

**Comment by iloveitaly** [comment]
For others looking at this issue `Restforce.log = true` will output all of the raw HTTP requests & responses.
