### ISSUE TITLE
API_DISABLED_FOR_ORG: The REST API is not enabled for this Organization.

### ISSUE THREAD

**Issue by vincenzor** [ejholmes/restforce#219]
Hi,

We give the possibility to our customers to connect their Salesforce account with our app.

One of our customer always get this error:
API_DISABLED_FOR_ORG: The REST API is not enabled for this Organization.

Do you have any idea to fix this?

**Comment by timrogers** [comment]
You’ll need them to contact Salesforce - I think the API is usually a paid feature.

**Comment by vincenzor** [comment]
OK, I'll try to do that. Thank you!
