### ISSUE TITLE
Demo App

### ISSUE THREAD

**Issue by antwonlee** [ejholmes/restforce#236]
Hey @timrogers I am making a demo Rails app with Restforce.  Perhaps I thought it will be a good resource for people who are trying to use the gem.  Sometimes code is better than README files.  Here is the repo: https://github.com/antwonlee/restforce_demo_app  I just started working on it whenever I got some free time.  I will create a pull request adding it to README when its done.

It will have basic CRUD functionalities using Restforce to interact with Salesforce data (Accounts, Contacts, Opportunities, Leads).  It has a dev Salesforce instance too where people can see the set up there too.

I thought it would be a good idea to write a short instruction on Oauth process (how to get refresh_tokens, etc) as well so people are not drowning in Salesforce documentations.

Let me know what you think.

**Comment by kris-luminar** [comment]
Seems like a very useful project. I would have used it when I began using Restforce if it had existed.

**Comment by antwonlee** [comment]
Awesome, I think there are few demo apps out there already—but I think I will document better and have basic CRUD functions for Accounts, Contacts, Opportunities, and Leads.  :sunglasses:

**Comment by kris-luminar** [comment]
💯
