### ISSUE TITLE
Define client ?

### ISSUE THREAD

**Issue by Sashkan** [ejholmes/restforce#252]
Hello,

That might sound stupid, but, where's the best place to define the client ?

The wiki just mentions a 
```
client = Restforce.new
```

I would like to set it globally accross my app, but setting it in ApplicationController doesn't seem to work. So far I set it in every controller everytime I need it, but is there a way to set it as a global variable?

Thanks

**Comment by timrogers** [comment]
@Sashkan What's going wrong when you try to set it in `ApplicationController`? That should work.

You have two options for global configuration - you could set it in an initializer (see https://github.com/ejholmes/restforce#global-configuration) or you could use environment variables (see https://github.com/ejholmes/restforce#usernamepassword-authentication). Once the client has been globally configured, `Restforce.new` will return a ready-to-use client.

**Comment by timrogers** [comment]
(To be clear, I'd probably advice using global configuration - it's a better option for your use case)

**Comment by Sashkan** [comment]
Thanks ! Worked just fine. One last question if I may: I managed to use all of the functions for basic functionnalities (create, destroy, update, etc..). However, is there a way to see the possible arguments/options related to a model ?)

I.E, my Opportunity model got Contacts. On my Salesforce Dashboard, I can see the "Contact Roles" tab on the right. From here, I can add contacts to my opportunity, But I can't find a way to do so using the gem. Using this:

```
client.create!('Opportunity', StageName: 'Brief Generated', CloseDate: Date.today, Name: 'Test Staging', AccountId: '0015800000FkKILAA3', Contacts: ["0035800000EtEUVAA3"])
```
tells me that 
```
No such column 'Contacts' on sobject of type Opportunity
```
I tried 
```
client.describe('Opportunity')
```

But this doesn't show any relationship.

**Comment by timrogers** [comment]
I'm afraid I'm not sure - probably the Salesforce API documentation is the
right place to look

--

*Tim Rogers*
GoCardless.com <https://gocardless.com>

**Comment by Sashkan** [comment]
If anyone gets this problem, all you have to do is
- ``` rails c```
- ```client = Restforce.new``` 
- ```client.describe([Your model])```
- ```Ctrl + Shift + F``` in your terminal, type the name of the field you're looking for
- ```Make sure you type the exact ```name``` 

In my case, the ```brief_need``` field turned into ```brief_need__c``` on my opportunity

**Comment by timrogers** [comment]
Custom fields will always have that `__c` prefix - you can definitely see those in the Salesforce interface too if you look at the fields for your object in settings!
