### ISSUE TITLE
Does Restforce handle the Revenues ?

### ISSUE THREAD

**Issue by Sashkan** [ejholmes/restforce#256]
Whenever you log into your Salesforce account, first thing you see is the Revenue Graph. 

I was wondering if ```Restforce``` had a method to handle this (so that everytime I close an opportunity, it should update the graph).

**Comment by timrogers** [comment]
I'd suggest asking Salesforce maybe - I don't think we have this graph in our accounts, but we might have got rid of it. You'd just need to ask them if it's exposed via the REST API.
