### ISSUE TITLE
not compatible with json 2.0 (and thus ruby 2.4)

### ISSUE THREAD

**Issue by ccutrer** [ejholmes/restforce#260]
JSON 2.0.0 dropped support for ruby < 2.0.0, but is otherwise compatible. JSON 2.0.0 is required to be compatible with Ruby 2.4. Thus until restforce updates its dependency constraint, restforce is not compatible with ruby 2.4

**Comment by timrogers** [comment]
@ccutrer Good spot! Have you tried with JSON 2.0.0? What's broken?

**Comment by ccutrer** [comment]
I haven't yet. I'm working on just trying to run our app with Ruby 2.4, and I have several other dependency problems to work through first. restforce is an optional feature in our app, so I just moved that code out for now. AFAICT, though, nothing should be broken - the only reason for the major version bump was dropping of ruby 1.8/1.9 support. Which you don't even need to worry about, as long as your dependency requirement still allows json < 2.0, then the consumers of your gem can pick the version of json that will work with the version of ruby they're using.

**Comment by timrogers** [comment]
I'll have a play now and see if it works - I imagine it will...

**Comment by timrogers** [comment]
I've put together a fix to this in https://github.com/ejholmes/restforce/pull/261 - looks like it's behaving well with the tests passing on all versions.
