### ISSUE TITLE
Cannot update to v2.4.1 on Rails v4.2 and Ruby v2.x

### ISSUE THREAD

**Issue by janraasch** [ejholmes/restforce#264]
Bc. of the change introduced in

https://github.com/ejholmes/restforce/commit/e21754baca178312b3063911de12d0930c0471d1

users of `rails (~> 4.2)` cannot upgrade to `restforce v2.4.1`.

The problem is a conflict with `activesupport`:

```bash
    rails (~> 4.2) was resolved to 4.2.7.1, which depends on
      railties (= 4.2.7.1) was resolved to 4.2.7.1, which depends on
        activesupport (= 4.2.7.1) was resolved to 4.2.7.1, which depends on
          json (>= 1.7.7, ~> 1.7)
```

I would hope that we could update to future versions of `restforce`, even when running `rails 4.2` on `ruby 2.x`. `rails v5` has been released but I think a lot of people might still be migrating.

**Comment by timrogers** [comment]
@janraasch Apologies! This will be fixed in v2.4.2 soon - awaiting a review on https://github.com/ejholmes/restforce/pull/262.

**Comment by timrogers** [comment]
Could you try binding your Gemfile to that commit and seeing if it works okay? :smile:

**Comment by janraasch** [comment]
Sure, works like a charme. Looking forward to the next release, then. Thank you.
