### ISSUE TITLE
"NOT_FOUND: The requested resource does not exist" on some commands

### ISSUE THREAD

**Issue by ncino-cpezza** [ejholmes/restforce#269]
When I am creating a select() or find() call I am receiving the above error when no records are found. but runs fine when there is a record to be returned. Any ideas on why this is happening only for these 2?

I am using gem version 2.4.2
Ruby 2.3.1 and rails 5.0.1

**Comment by swaincreates** [comment]
I believe thats the correct response and it is similar to running an ActiveRecord find method. For instance with ActiveRecord `User.find(1235)` will return `ActiveRecord::RecordNotFound: Couldn't find User with 'id'=1235`.

**Comment by ncino-cpezza** [comment]
So there is no way to have it return false instead of error when running these methods? Trying to check for existing record before doing and update or create. Upsert can't work when lookup field is master detail not reparenting.

**Comment by swaincreates** [comment]
I may not understand your full situation, but you can rescue the specific error and get a similar check. Something like:

```ruby
begin
  client.find('Contact', 'bad_id')
rescue Faraday::ResourceNotFound
  # code if find fails
end
```

**Comment by ncino-cpezza** [comment]
Ahh ok ill give that a go thanks!

**Comment by timrogers** [comment]
@swaincreates's suggestion is 👌  - that's what I do! Just let us know if you come up against any other issues at all.
