### ISSUE TITLE
Upgrade to faraday 0.10?

### ISSUE THREAD

**Issue by maxwell** [ejholmes/restforce#280]
First: Thank you for restforce, it saves me loads of headaches and I appreciate all the hard work you guys do.

I am working on upgrading my app to Rails 5; any chance of supporting the most recent version of Faraday as your dependency?

Thank you!

**Comment by timrogers** [comment]
@alexluke is on it in #278 - should get it merged soon :heart:

**Comment by timrogers** [comment]
Done!

**Comment by maxwell** [comment]
thank you!
