### ISSUE TITLE
Faraday::ClientError: (error code missing)

### ISSUE THREAD

**Issue by nojose** [ejholmes/restforce#290]
Hi. I have an app on Rails 4.2.6, Ruby 2.2.2 using Restforce 2.2.0 that has been running, for almost a year, a background task (every hour) that performs some updates on Salesforce.  

`@client = Restforce.new( { api_version: '32.0', host: ..., username: ..., password: ..., client_id: ..., client_secret: ...})`
`@client.update('Student_Volume__c', {...})`

The update call is inside a loop of ~50 iterations (so we make 50 calls to SF API every hour). In the past few days, we have been receiving errors that the call fails sometimes. Looking closely into it, we ran the same set of data multiple times only to find out that sometimes all the request were successful, but many others one or more of the request failed (randomly, every time it was a different one). We updated to the latest version of the gem (2.5.0) but the issue wasn't fixed.

The error it is throwing is: _Faraday::ClientError: (error code missing)_ and sometimes it prints this:

_<body>
503 org.eclipse.jetty9.servlet.ServletHolder$1: java.lang.IllegalStateException: About-to-be-created singleton instance implicitly appeared through the creation of the factory bean that its bean definition points to</body>_

We are almost certain this in an issue on Salesforce API (as I said, we didn't make any changes to the app), but wanted to know if someone else is experiencing this issue using Restforce.

Thanks in advance.

**Comment by nojose** [comment]
We aren't. We are going directly to Salesforce endpoint. I'll go the their forums to see if someone else is having this issue. Thanks!

**Comment by timrogers** [comment]
Let us know what to find out! The message your getting certainly won't have
come from Ruby ❤
