### ISSUE TITLE
Faraday::TimeoutError - within seconds

### ISSUE THREAD

**Issue by JaisonBrooks** [ejholmes/restforce#294]
So i just started experiencing this issue yesterday. Its all across my Rails application. Every Restforce query returns this error. When performing even the simplest query, within seconds the query times out. 

Im using restforce (2.5.0) with Ruby 2.2.3 and Rails 4.2.4. let me know what else you may need in order to help. Im at loss right now.

Here the example query...
`sfdc.client.query("select Id, Name from Contact")`
Faraday::TimeoutError: Net::ReadTimeout

**Comment by timrogers** [comment]
I'd check any global configuration you have for Faraday or Net::HTTP across your project (e.g. in `config/initializers` - looks like some kind of networking problem. Can you try from another machine or network too?

**Comment by JaisonBrooks** [comment]
I have resolved the issue. You were on the right track, i had an issue a TIMEOUT environment variable being set to 0. therefore every restforce query resulting in this error. I am now setting my own timeout when creating my restforce client and it works good. Maybe suggestion in the future, valid timeout is set to value above 0? not sure anyone would ever proactively set it to that.
