### ISSUE TITLE
Check if connection is present

### ISSUE THREAD

**Issue by kevinjbayer** [ejholmes/restforce#307]
I can look for an access_token being present in the database, but is there an easy way to tell if the RestForce object is connected or not? Doing something like client.user_info.present? fails when an instance doesn't exist.

**Comment by timrogers** [comment]
Can you provide a code example to explain what you mean? I'm not sure I
understand what you mean by a Restforce object being connected, so I think
that'll help.

**Comment by kevinjbayer** [comment]
Sure! So, I'm establishing `@restforce = Restforce.new...` in my controller. With or without the access token, @restforce creates an object that exists, but doesn't necessarily have a connection to salesforce. In my view, if I do `if @restforce.user_info.present?`, this will fail if the connection doesn't exist. I can also do `if @user.sf_token.present?`, which works, but relies on the token being present, whereas I'd like to rely on the connection to Salesforce itself being present. `@restforce.present?` is true, even if the access token doesn't exist. Make sense?

**Comment by timrogers** [comment]
By a valid connection, do you mean that you have an access token that
allows you to successfully make requests to Salesforce? If so, I think
using #user_info is probably the best bet.

**Comment by kevinjbayer** [comment]
Ok, I just wanted to make sure there wasn't some easier, safer method that I was missing. Thanks, Tim!
