### ISSUE TITLE
is it possible for restforce to address the Database emptyRecycleBin method? 

### ISSUE THREAD

**Issue by chrismcmahon** [ejholmes/restforce#309]
The method I would like to call from restforce: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_database.htm#apex_System_Database_emptyRecycleBin_3

When I attempt this with for example 

@api_client.emptyRecycleBin(array_of_ids)

the result is 

undefined method `emptyRecycleBin' for #<Restforce::Data::Client:0x007fc1b8eec448> (NoMethodError)

Reading the docs, I think the reason has to do with the difference between "Database" and "DML", as the documentation says "Some Database methods also exist as DML statements" and restforce addresses "DML".  I am hoping there is a mechanism by which restforce can also address "Database".

**Comment by timrogers** [comment]
I'm afraid I don't think it is - sorry! `emptyRecycleBin` is an Apex method which you can run inside of Salesforce, rather than a piece of functionality exposed in the REST API.
