### ISSUE TITLE
Restforce + Bulk Api

### ISSUE THREAD

**Issue by erlandsona** [ejholmes/restforce#312]
I'm trying to take advantage of Salesforce's Bulk Api to do this [`backup.objects=*`](https://github.com/neowit/backup-force.com/blob/c927b0f7ab36ffd3f7e7c7223ca3e858c391549e/config/sample-configuration.properties#L64) ([context](https://github.com/neowit/backup-force.com/blob/c927b0f7ab36ffd3f7e7c7223ca3e858c391549e/src/main/scala/com/neowit/apex/backup/BackupRunner.scala#L102))

But I'm not a Scala dev and this should be relatively straightforward by looping over `client.list_sobjects` passing each into it's own call to something like [Restforce::Bulk::Job.create(:query, sobject, :csv)](https://github.com/dtmtec/restforce-bulk/tree/9ef016027e79f97b140f0cb4beeb15d8944c97e4#query)

My primary issue is restforce-bulk doesn't seem to be maintained so... is there a way to query the Bulk Api without the need for restforce-bulk? 

And take advantage of compressed responses?

**Comment by timrogers** [comment]
I'm afraid the Bulk API isn't supported by this gem; it's only for the REST API. Sorry! :sob:

**Comment by erlandsona** [comment]
😞 Thanks anyways! I'm still using it for authentication which it makes super easy, so thanks for that!
